### ISSUE TITLE
Move over work from Jupyter RTC 

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/rtc#1]
We should move code from https://github.com/jupyterlab/jupyterlab/pull/6871 to this repo and close that PR

**Comment by ian-r-rose** [comment]
I'm not sure what code you are referring to? Do you mean the server-side stuff? Most of the model refactor is specific to JupyterLab, so I don't know why we would abandon that PR.

**Comment by saulshanabrook** [comment]
OK we can keep the PR open, but eventually it would be refactored to use the packages in this repo. So I wanna pull your table schema stuff into this repo as well as the server side patch server.
