### ISSUE TITLE
Make table finalization explicit

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/rtc#26]
Before we connect to the datastore relay, we need a list of all the tables with schemas. Otherwise, we cannot read the transactions. A choice was made a while ago to make the schemas implicit, meaning that all clients need to share the sames schemas to be able to work together on the same datastore.

So currently, I thought I could be clever and implicitly finalize the list of tables when we start doing transactions. The user story I was thinking about was a number of modules all registering tables in their global scope, and then a react component that gets data from the datastore with a table that was registered. So this implicitly assumes all modules are loaded before any components are rendered.

In Python, this maybe isn't too crazy and is a normal thing to do. However in JS, it's probably a bad idea for a couple reasons, one of them being modules can be lazy loaded. So instead, it's probably best to have an explicit connection stage, where you pass in all the tables you want to register. 

So we should make the whole thing a bit simpler/dumber and just have you initialize the datastore with a list of tables. More like the datastore in lumino. And then for react integration, throw a datastore on the react context, like [`RecoilRoot`](https://recoiljs.org/docs/api-reference/core/RecoilRoot).

For JupyterLab, assuming we want just one large datastore for everyone, we would need some plugin that lets you register a new schema, and then a promise that resolves with the datastore, once all the schemas have been added and it has connected.

**Comment by vidartf** [comment]
> For JupyterLab, assuming we want just one large data table for everyone

I'm not sure I understand what the assumption is. What does "table" mean in this context?

**Comment by saulshanabrook** [comment]
> I'm not sure I understand what the assumption is. What does "table" mean in this context?

Sorry I misspoke, I meant datastore.
