### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by joequant** [jupyterlab/rtc#35]
Great meeting you all at the last meeting.

Looking for a wiki or bulletin board that we can start posting things.  I've got a lot of unstructured information and I think just having everyone dump what they are doing onto a wiki and then organizing things would be the way to put some order into the glorious chaos.  :-) :-) :-)

**Comment by saulshanabrook** [comment]
Totally that sounds good!  Does the wiki on this repo suffice?

**Comment by joequant** [comment]
Yes the wiki here would work just fine.  What I'd like to do is to do a brain dump of what I'm working on.  Have other people do brain dumps on what they are working on, and then step back and put together the pieces.

**Comment by saulshanabrook** [comment]
Great! You should have access to add things to the wiki here? Feel free to put all you want there.

**Comment by joequant** [comment]
When i click on wiki, it bumps me back to the home page.  Does an admin need to create a home page?

**Comment by saulshanabrook** [comment]
I created a first page, try it now?

**Comment by joequant** [comment]
i think you have to change the permissions:

https://help.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis

**Comment by saulshanabrook** [comment]
Yep, sorry about that. Should work now!

**Comment by joequant** [comment]
Thanks!!!!
