### ISSUE TITLE
Merging permissions are too permissive

### ISSUE THREAD

**Issue by ianhi** [jupyterlab/rtc#46]
If I look at at a PR I seem to have the ability to merge it:
![image](https://user-images.githubusercontent.com/10111092/86977646-178c4c80-c14b-11ea-8be1-33d8b129fa27.png)

however this seems incorrect as no such power was ever explicitly granted. I was added to jupyterlab/triage (https://github.com/orgs/jupyterlab/teams?query=%40ianhi) which I suppose must have given me this access. 

On the main jupyterlab repo I do not have the ability to merge (which seems correct)

**Comment by ianhi** [comment]
Oh wow, actually I think this applies to all repos in jupyterlab except for the main jupyterlab repo

**Comment by saulshanabrook** [comment]
Oh woops, yeah I realized I changed it for the org instead of changing it just for the repo... 

I changed it back to the default of "read". Thank you for opening this.

<img width="2048" alt="Screen Shot 2020-07-09 at 10 45 23 AM" src="https://user-images.githubusercontent.com/1186124/87054602-4d741400-c1d1-11ea-85b5-d74d9a2d18d9.png">

I guess I will just add people individually in the org to be admins here.

**Comment by saulshanabrook** [comment]
Thanks again for opening this here! If anyone else could use write/admin access, please ping me (here or directly) and I can add you.

**Comment by ianhi** [comment]
> Thank you for opening this

I feel a bit like the kid reminding the teacher about homework :joy: 

Also, I don't think that that fixed it. I seem to still have this ability:
![image](https://user-images.githubusercontent.com/10111092/87109307-4b8e6d00-c232-11ea-8bed-be0ba09cbd55.png)

**Comment by saulshanabrook** [comment]
It's an org wide setting, I thought I changed it to read yesterday, but looks like either someone else changed it to write or I miss clicked. I changed it back to read.

**Comment by ianhi** [comment]
Yeah I think someone else must've changed it back because I think at first it was removed.

**Comment by ianhi** [comment]
@saulshanabrook maybe as a consequence of this I seem to now have lost triage rights on everything except the main jupyterlab repo. Not sure if that was intentional or not, but thought I'd note it. (was helpful for jupyterlab-git)

**Comment by saulshanabrook** [comment]
Huh interesting, I am not sure how to fix that... 

These are the only options available:

![Uploading Screen Shot 2020-07-10 at 12.02.11 PM.png…]()

**Comment by ianhi** [comment]
I believe you that there are limited option but I can't actually see - seems the screenshot didn't finish uploading

**Comment by ianhi** [comment]
Maybe it was always the case that triage members could merge in the other repos?

**Comment by saulshanabrook** [comment]
<img width="1022" alt="Screen Shot 2020-07-10 at 12 10 33 PM" src="https://user-images.githubusercontent.com/1186124/87175224-5da9f300-c2a6-11ea-9863-8c35fd5979d8.png">

**Comment by ianhi** [comment]
Wild. How does it work for the main jupyterlab repo? triage rights were retained there
