### ISSUE TITLE
Add CRDT talk to docs as a resource

### ISSUE THREAD

**Issue by willingc** [jupyterlab/rtc#50]
https://martin.kleppmann.com/2020/07/06/crdt-hard-parts-hydra.html

**Comment by willingc** [comment]
Interesting project mentioned by @ellisonbg in weekly meeting: https://github.com/yjs/yjs

**Comment by echarles** [comment]
Thx @willingc. There is also https://github.com/jupyterlab/rtc/issues/15 that lists other ver interesting resources aimed to be added to a README.

I will pull them in the RDT with https://github.com/jupyterlab/rtc/pull/48

**Comment by echarles** [comment]
Integrated in the docs.
