### ISSUE TITLE
Use @jupyter-rtc/... as packages name

### ISSUE THREAD

**Issue by echarles** [jupyterlab/rtc#58]
Should we prepend `@jupyter/` to the package name?

e.g. `rtc-node` -> `@jupyter/rtc-node`

cc/ @saulshanabrook

**Comment by echarles** [comment]
or have our own `@jupyter-rtc` namespace? 

`rtc-node` -> `@jupyter-rtc/node`
`rtc-debugger` -> `@jupyter-rtc/debugger`

Sounds to me better.

**Comment by saulshanabrook** [comment]
Yeah second option sounds good! I intentionally left out a prefix to start with because I wasn't sure where these would end up. Before we actually publish any of the packages, we should figure this out.

**Comment by afshin** [comment]
You can create an NPM namespace without creating a new GitHub organization. Creating a new GitHub org would require a JEP and it has implications in the new governance model as well, but simply creating a prefix is straightforward, the way we did with `@lumino/*`.

**Comment by echarles** [comment]
Should we create a npm `@jupyter-rtc` org (https://docs.npmjs.com/creating-an-org) and leave this repo in github jupyterlab for now?

**Comment by afshin** [comment]
I think that's a good plan because it won't dictate what we do in the future and helps organize the package names right away.

**Comment by saulshanabrook** [comment]
Sure. Just FYI it doesn't matter what we call it until we are actually using these packages external from this repo. Until that time, they don't have to be published.

**Comment by echarles** [comment]
NPM `@jupyter-rtc` org is created. Can you give me your npm account username so I add you to the org? Thx.

**Comment by saulshanabrook** [comment]
saulshanabrook
