### ISSUE TITLE
Build RTC on-merge in main branch

### ISSUE THREAD

**Issue by echarles** [jupyterlab/rtc#62]
It would be good to automate the docs building on each merge of the main/master branch, especially because we iterate in this inception phase.

**Comment by saulshanabrook** [comment]
That sounds good! Is it set up on Read the Docs to auto build?

**Comment by echarles** [comment]
I have gone through the RTD settings but have not found how to do that. Maybe you or @willingc can have a look? Thx!

**Comment by saulshanabrook** [comment]
I think I fixed it!

<img width="1114" alt="Screen Shot 2020-07-20 at 12 06 31 PM" src="https://user-images.githubusercontent.com/1186124/87959810-745c0100-ca81-11ea-8701-4480c1f3abba.png">


https://github.com/jupyterlab/rtc/pull/64  https://jupyter-rtc--64.org.readthedocs.build/en/64/

Following [this guide](https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html#troubleshooting) I had to:

1. Delete the Read the Docs integration from my personal github account.
2. Remove the github integration from my Read the Docs account
3. Re-add the github integration, making sure to grant access to the `jupyterlab` org
4. Re-add the webhook for the repo from the Read the Docs admin page

**Comment by willingc** [comment]
@saulshanabrook @echarles Looks like you got it resolved. Adding a webhook is the right step. If for some reason it doesn't work, please ping me.

**Comment by echarles** [comment]
This is fixing `Build on Pull Request` which was indeed not working, and create a dedicated site on https://jupyter-rtc--64.org.readthedocs.build/en/64/ with a warning message `This page was created from a pull request.`

<img width="931" alt="Screenshot 2020-07-20 at 19 55 12" src="https://user-images.githubusercontent.com/226720/87969722-f28cc780-cac2-11ea-8f00-c3f3334b1e99.png">

Does it also build when merging to master (which is what I was aiming with this issue)?

**Comment by saulshanabrook** [comment]
> Does it also build when merging to master (which is what I was aiming with this issue)?

Yeah it builds the `main` branch as well, I believe?

**Comment by willingc** [comment]
Just an FYI, the warning only displays on pull requests and is not seen once the PR is merged. https://docs.readthedocs.io/en/latest/guides/autobuild-docs-for-pull-requests.html#features

**Comment by echarles** [comment]
Wonderful @saulshanabrook. Thx for your continuous support @willingc
