### ISSUE TITLE
Rename master to main branch

### ISSUE THREAD

**Issue by echarles** [jupyterlab/rtc#63]
Would be good to rename `master` branch to `main` to remove slavery reference.

**Comment by saulshanabrook** [comment]
Sounds good to me.

**Comment by schuelermine** [comment]
It's not a slavery reference though. It's a word that designates superiority in some sense. That was used to describe slave owners back in the day, but then again, so was the word "human". The meaning of "master" still applies to the master branch. But then again it doesn't really matter. Main works too.

**Comment by echarles** [comment]
<img width="569" alt="Screenshot 2020-07-20 at 17 38 52" src="https://user-images.githubusercontent.com/226720/87956959-f2370100-caaf-11ea-8fc2-7e0a86b0f966.png">

Done.
