### ISSUE TITLE
reddit discussion on collaborative jupyter notebooks

### ISSUE THREAD

**Issue by williamstein** [jupyterlab/rtc#65]
There's an active reddit discussion right now about jupyter rtc:

https://www.reddit.com/r/datascience/comments/i5hj2o/multi_user_collaborative_notebook/

I posted a message advertising the existence of jupyterlab-rtc there, since people will probably find that thread via Google in a few months when it is no longer possible to comment on it:

"For people who find this thread in a year, I also want to advertise the JupyterLab RTC project, which currently has a lot of momentum around adding multi-user editing functionality to JupyterLab itself.  There's excellent regular meetings, tons of documentation about their approach, community building, etc. https://github.com/jupyterlab/rtc  It's not helpful for people who need realtime collaboration *today*, but in a year (or maybe a few months), it could be incredibly helpful."

NOTE: This is the sort of information I would normally fire off to a mailing list, but jupyterlab/rtc doesn't seem to have a mailing list.  So I guess as an issue the action items for this are: 
- [x] add a link to the reddit discussion somewhere in the jupyterlab/rtc doc pages, and
- [ ] some people look at the reddit thread and maybe comment on it if necessary...  

Again, sorry if it is annoying opening this as an issue.

**Comment by saulshanabrook** [comment]
Thanks @williamstein!

I don't mind using issues as notes and discussion points. I added the `type:discussion` label to this one.

I think it would make sense to add a link from the docs as well, as you suggested.

**Comment by echarles** [comment]
Thx @williamstein I have added the link on https://jupyter-rtc.readthedocs.io/en/latest/about/user-stories.html and checked the first action point in your first comment.

For the second action point (engage on the reddit thread), as you said in your reddit post, we may have something to offer in 1 year (or a few months...). 

Thx again for your contributions in this community.
