### ISSUE TITLE
JupyterCon 2020 Talk - Jupyter Real Time Collaboration

### ISSUE THREAD

**Issue by echarles** [jupyterlab/rtc#78]
We have been accepted for a talk at [JupyterCon 2020](https://jupytercon.com) 👍 

Any feedback, comment... on the following details are very welcome.

Title: Jupyter Real Time Collaboration

Jupyter Community: Tools and Practices Talk

Audience level : Intermediate

Brief summary: Looking for a "Google Docs"-type experience for your notebooks? Then this talk is for you... You will get a detailed status of the Jupyter RTC (Real Time Collaboration) official project and how it is used for JupyterLab. You will also get details on the underlying algorithms and learn how to integrate Jupyter RTC in a custom React.js application.

Outline: Jupyter RTC is a set of javascript libraries and server components that can be used to transform the classical notebook experience into a real-time collaborative solution where multiple users can write and run simultaneously Jupyter notebooks. This feature give the users a "Google Docs"-type experience. The official Jupyter initiative is hosted on https://github.com/jupyterlab/rtc and documented on https://jupyter-rtc.readthedocs.io. This talk will educate and inform the audience on the goals, requirements and status of this project. We will articulate the talk in three parts. The first part is about sketching the initiative and RTC goals. We will highlight typical use cases, introduce the team and give a demo of the solution with JupyterLab. With the second part, we will go into a deeper technical review of the underlying algorithms and technology, comparing the various approaches and review existing implementations outside of Jupyter. Finally, as Jupyer RTC is a library, we will demonstrate how to use it to build your own custom application in React.js.

**Comment by williamstein** [comment]
- "get an detailed " --> "get a detailed"

-  "a real collaborative" - "a real-time collaborative"

- "This feature give sthe users" --> "This feature gives the users"

- "This talk will about educating and informing " --> "This talk will educate and inform "

Thanks for preparing this talk, which I'm very much looking forward to listening to!

**Comment by echarles** [comment]
Thx @williamstein. I have fixed the typos in the first comment. I will post a link to some slides as soon I have them.

**Comment by flutefreak7** [comment]
Found the video on YouTube! https://www.youtube.com/watch?v=mUGUxWZjR7E

I was a little disappointed that the [conference website page](https://cfp.jupytercon.com/2020/schedule/presentation/116/jupyter-real-time-collaboration/) didn't link to video. 

Also there's a [JupyterHub youtube](https://www.youtube.com/channel/UCk4mxleDfaMqdm5kHISD3qA), but I think it only includes videos from the hosts.

Figured I would share in case others find this discussion and want to see the video.

**Comment by echarles** [comment]
Thx for the link @flutefreak7
