### ISSUE TITLE
tsconfig to support declaration and isolatedModules

### ISSUE THREAD

**Issue by echarles** [jupyterlab/rtc#85]
Running the examples forces a change for `isolatedModules` to `true` which conflicts with `declaration` being `true`.

It is fine that the examples do not generation declaration, just want to double discuss this here so we converge to a well defined `tsconfig-base.json`.

**Comment by saulshanabrook** [comment]
Yeah for examples we don't need declarations, but for other packages we do need to ship them, right? So that downstream consumers get TS types?

**Comment by echarles** [comment]
Yes, examples do not need to generate declarations. `tsconfig.base.json` has `"declaration": true,`, which is what we need for most packages.

Closing this as we are not the same line.
